### ISSUE TITLE
Move relationships and file types outside source code

### ISSUE THREAD

**Issue by gkapi** [eellak/clio#12]
if feasible, I think it would be better to move the content of valid_relationship and valid_delivery outside the source code, so that the options are not hardcoded (since they might change in the future).
[https://github.com/eellak/clio/blob/master/src/specification.py](url)

**Comment by gopuvenkat** [comment]
Please provide suggestions on where we can maintain such information.

**Comment by gkapi** [comment]
I would even add it to the DB, but otherwise it can be an external file on the server.
