### ISSUE TITLE
No progress bar in populate_dp.py

### ISSUE THREAD

**Issue by shivanshuraj1333** [eellak/clio#34]
On running populate_dp.py to populate database no progress is shown in console, which is very inconvenient to monitor progress as this process takes appreciable amount of time to complete.

![Screenshot from 2019-03-10 11-43-52](https://user-images.githubusercontent.com/26167974/54081362-e66af480-4329-11e9-8d46-e92ab7a9eaea.png)

- [ ] Add progress bar (like the one shown in the gif) in populate_db.py

> This improvement will help developer not user

![Screencast2019031012_05_15](https://user-images.githubusercontent.com/26167974/54081619-92faa580-432d-11e9-9bd3-90010ca3a282.gif)

**Comment by gopuvenkat** [comment]
This would be useful for a developer (while seeding the database). Are you planning on using `pyprind.ProgBar`?

**Comment by shivanshuraj1333** [comment]
No, I was tinkering with tqdm. Both seem fine.

**Comment by JayeshShukla** [comment]
@zvr Hi,
I am Jayesh Shukla from Chennai, India. I would love to work with GFOSS in GSOC 19 as it excites me the most.Would be really great if you guide me how get started and start contributing now onwards. Also I would like to work on the this clio project as it drags my attention the most.I would also appreciate @gopuvenkat's help if u can. Thanks a lot guys!!!

**Comment by gopuvenkat** [comment]
Hi @JayeshShukla,
Clio is built on Flask framework (language - Python3). Please follow the installation guide provided [here](https://github.com/eellak/gsoc2018-clio/wiki/Installation) to setup the local development environment (along with the required LDAP configuration).
When contributing to this repository, please first discuss the change you wish to make via the Issues page or through Zulip chat.

**Comment by zvr** [comment]
As it was stated above, this will only help the developer, so it should be done in the lowest priority.
And we should be _very_ careful about adding even more dependencies, especially since they do not help the users.
If this was really needed, it could of course be implemented without adding anything by `print`.
