### ISSUE TITLE
Improvement for license page 

### ISSUE THREAD

**Issue by Chinmay-Gurjar** [eellak/clio#38]
The link given in the license text is not clickable, user has to copy the link manually and copy in browser to view complete license.

![Screenshot from 2019-03-17 12-25-26](https://user-images.githubusercontent.com/46123009/54492522-67f3f100-48ed-11e9-9c3a-2248eb5cad3c.png)

**Comment by Chinmay-Gurjar** [comment]
can I work on this issue ?

**Comment by zvr** [comment]
The "Text" entry should ideally contain the actual text of the license -- which can be obtained from the SPDX data dump.
We can also have a link to the SPDX page, on another field ("SPDX link" or something).

**Comment by Chinmay-Gurjar** [comment]
I added a "click here to go to license" button after the license text.
