### ISSUE TITLE
update license data to SPDX license list v3.4

### ISSUE THREAD

**Issue by zvr** [eellak/clio#42]
SPDX license list v3.4 was published on 208-12-20.
The initial loaded data should reflect this.

**Comment by zvr** [comment]
Data is available in https://github.com/spdx/license-list-data

**Comment by Chinmay-Gurjar** [comment]
Is a csv file with initial data from https://github.com/spdx/license-list-data required ? @zvr

**Comment by shivanshuraj1333** [comment]
No, CSV file is no more needed if you're planning to automate data population in database.
CSV file is used in the project to initially populate database, which is no more needed. You may use json file from github repository to populate database.

**Comment by zvr** [comment]
This ticket is about updating the data in the repo.
This can be implemented in different ways:
1. providing an updated csv in `src/dataset/license-info.csv`; or
2. providing the data in another format from https://github.com/spdx/license-list-data AND providing the corresponding code to read it in `src/populate_db.py`

Probably doing 1 is easier...

**Comment by Chinmay-Gurjar** [comment]
So, I already have the updated csv should I submit a PR uploading the csv ?

**Comment by zvr** [comment]
Sure, if you have the new data...
